PROJETO/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('drugs.urls'))
]

drugs/urls.py
from django.urls import path

from drugs.views import home

urlpatterns = [
    path('', home),
]

meuprojeto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/search/', views.search, name="search"),
    path('recipes/category/<int:category_id>/',
         views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

drugs/models.py
from django.db import models

# Create your models here.

recipes/models.py
from email.policy import default
from wsgiref.simple_server import demo_app

from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None
    )
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.title

drugs/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'drugs/home.html')

recipes/views.py
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render

from .models import Recipe


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
    })


def category(request, category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True
        ).order_by('-id')
    )

    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes,
        'title': f'{recipes[0].category.name} - Category |'
    })


def recipe(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,
    })


def search(request):
    search_term = request.GET.get('q', '').strip()
    if not search_term:
        raise Http404()
    return render(request, 'recipes/pages/search.html', {
        'page_title': f'Search for "{search_term}" |',
    })

drugs/templates/drugs/home.html
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
        integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css"
        integrity="sha512-OivR4OdSsE1onDm/i3J3Hpsm5GmOVvr9r49K3jJ0dnsxVzZgaOJ5MfxEAxCyGrzWozL9uJGKz6un3A7L+redIQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/solid.min.css"
        integrity="sha512-qzgHTQ60z8RJitD5a28/c47in6WlHGuyRvMusdnuWWBB6fZ0DWG/KyfchGSBlLVeqAz+1LzNq+gGZkCSHnSd3g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Farmácia</title>
    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        html {
            font-size: 62.5%;
        }
    </style>

</head>

<body>
    <div class="main-container">
        <div class="box-container">
            <h1><i class="fa-solid fa-pills"></i> <i class="fa-solid fa-tablets"></i> Farmácia do Brasil <i
                    class="fa-solid fa-syringe"></i></h1>
        </div>
    </div>
</body>

</html>

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes  %}
        {% include 'recipes/partials/recipes.html' %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %} Home | {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes  %}
        {% include 'recipes/partials/recipes.html' %}
    {% empty %}
        <div class="center m-y">
            <h1>No recipes found here.😢</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %} {{ recipe.title }} | {% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'recipes/partials/recipes.html' %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/search.html
{% extends 'global/base.html' %}

{% block title %} {{ page_title }} {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
    {% for recipe in recipes  %}
        {% include 'recipes/partials/recipes.html' %}
    {% empty %}
        <div class="center m-y">
            <h1>No recipes found here.😢</h1>
        </div>
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://www.lfernando.dezorze@gmail.com.br/" target="_blank" rel="noreferrer noopener">By Fernando</a>
  </div>

  <div class="powered">
    <a href="https://www.lfernando.dezorze@gmail.com.br/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
  </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
        integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
        integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
        integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&family=Roboto+Slab:wght@900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
    

recipes/templates/recipes/partials/headers.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fas fa-solid fa-hospital main-logo-icon"></i>
                <span class="main-logo-text">Hospital do Brasil</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipes.html
<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="Temporário">
            </a>
        </div>
    {% endif %}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                {{recipe.title}}</h2>
            </a>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author %}
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{ recipe.author.username }}
                {% endif %}
            {% else %}
                 Desconhecido
            {% endif %}    
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
        </span>
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ recipe.category.name }}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation_steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{ recipe.preparation_steps|safe }}
            {% else %}
                {{ recipe.preparation_steps|linebreaksbr }}
            {% endif %}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'recipes:search' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{search_term }}" required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>